/* Aletheia Rice Intelligence v0.3: private browser-held portable ledger */
(function(){
'use strict';
var KEY='aletheia-rice-data-v1',SCHEMA='aletheia-rice-intelligence-data/v1',BT=String.fromCharCode(96),FENCE=BT+BT+BT;
var A='Aletheia Protocol: https://github.com/KarstenEvans/aletheia-protocol  \nThalia Protocol: https://github.com/KarstenEvans/thalia-protocol/blob/main/THALIA_PROTOCOL.md';
var state={schema:SCHEMA,runs:[],observations:[]},handles={};
var el=function(id){return document.getElementById(id)},safe=function(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})};
function notice(t){el('filesStatus').textContent=t}
function mdData(){return '# Aletheia Rice Intelligence - Data\n\n'+A+'\n\nPersonal observation archive. Retrieval time is NOT price observation date. Numeric candidates are unreviewed until you verify the original publication. Never publish a personal copy of this data file.\n\n'+FENCE+'json\n'+JSON.stringify(Object.assign({},state,{exported_at:new Date().toISOString()}),null,2)+'\n'+FENCE+'\n'}
function mdSettings(){if(typeof absorbFields==='function')absorbFields();return '# Aletheia Rice Intelligence - Settings\n\n'+A+'\n\nNo private Worker token is exported. Zero selected sources means no research.\n\n'+FENCE+'json\n'+JSON.stringify(Object.assign({},settings,{exported_at:new Date().toISOString(),settings_version:'0.3'}),null,2)+'\n'+FENCE+'\n'}
function parse(t){if(t.length>7500000)throw Error('File exceeds 7.5 MB');var m=t.match(/```json\s*([\s\S]*?)```/i);return JSON.parse(m?m[1]:t)}
function rec(x){if(!x||!['source-check','price'].includes(x.kind)||typeof x.source_id!=='string'||typeof x.retrieved_at!=='string')return null;var u;try{u=new URL(x.url);if(u.protocol!=='https:')return null}catch(e){return null}
 var r=Object.assign({},x,{url:u.href,source_name:String(x.source_name||'').slice(0,180),source_id:x.source_id.slice(0,100),retrieved_at:x.retrieved_at.slice(0,30),evidence:String(x.evidence||'').slice(0,600),status:String(x.status||'unverified').slice(0,100)});
 r.chart_eligible=x.status==='user-reviewed'&&x.chart_eligible===true;
 if(x.kind==='price'){r.grade=String(x.grade||'').slice(0,150);r.origin=String(x.origin||'').slice(0,60);r.basis=String(x.basis||'').slice(0,140);r.currency=String(x.currency||'').slice(0,12);r.unit=String(x.unit||'').slice(0,12);r.value=Number(x.value);if(!r.grade||!(/^\d{4}-\d{2}-\d{2}$/).test(x.observation_date||'')||!Number.isFinite(r.value)||r.value<=0||r.value>100000000)return null}
 return r}
function id(r){return r.kind==='price'?[r.kind,r.source_id,r.observation_date,r.grade,r.currency,r.unit,r.basis,r.value].join('|'):[r.kind,r.source_id,r.retrieved_at.slice(0,10),r.fingerprint||r.status].join('|')}
function store(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){notice('Storage unavailable or full: download your Data.md immediately.')}paint()}
function restore(){try{var raw=localStorage.getItem(KEY),v=raw&&JSON.parse(raw);if(v&&v.schema===SCHEMA)state={schema:SCHEMA,runs:Array.isArray(v.runs)?v.runs.slice(-500):[],observations:Array.isArray(v.observations)?v.observations.map(rec).filter(Boolean).slice(-2600):[]}}catch(e){notice('Could not restore browser history; use Load Data.md')}}
function importData(text){var v=parse(text);if(v.schema!==SCHEMA||!Array.isArray(v.observations)||!Array.isArray(v.runs))throw Error('Unknown Data.md schema');var map=new Map(state.observations.map(function(x){return[id(x),x]}));v.observations.forEach(function(x){var r=rec(x);if(!r)return;var old=map.get(id(r));map.set(id(r),old&&old.status==='user-reviewed'?old:r)});state.observations=Array.from(map.values()).slice(-2600);state.runs=Array.from(new Map(state.runs.concat(v.runs).filter(function(x){return x&&x.retrieved_at}).map(function(x){return[x.retrieved_at,x]})).values()).slice(-500);store();notice('Data.md merged and deduplicated; unreviewed prices remain excluded from graphs.')}
function importSettings(text){var v=parse(text);if(v.schema!==VERSION)throw Error('Unknown Settings.md schema');settings=normalize(v);save();buildSettings();paint();notice('Settings.md loaded; private Worker token was not imported.')}
function download(name,body){var url=URL.createObjectURL(new Blob([body],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},1500)}
function exportData(){download('aletheia-rice-intelligence-data.md',mdData());notice('Data.md downloaded. Retain your latest personal copy.')}
function exportSettings(){download('aletheia-rice-intelligence-settings.md',mdSettings());notice('Settings.md downloaded. The Worker access token is excluded.')}
function db(){return new Promise(function(ok,fail){var r=indexedDB.open('aletheia-rice-file-handles',1);r.onupgradeneeded=function(){r.result.createObjectStore('handles')};r.onsuccess=function(){ok(r.result)};r.onerror=function(){fail(r.error)}})}
async function handleSave(k,h){try{var d=await db();await new Promise(function(ok,fail){var t=d.transaction('handles','readwrite');t.objectStore('handles').put(h,k);t.oncomplete=ok;t.onerror=function(){fail(t.error)}})}catch(e){}}
async function handleLoad(k){try{var d=await db();return await new Promise(function(ok){var r=d.transaction('handles','readonly').objectStore('handles').get(k);r.onsuccess=function(){ok(r.result)};r.onerror=function(){ok(null)}})}catch(e){return null}}
async function load(k){if(typeof window.showOpenFilePicker==='function')try{var list=await window.showOpenFilePicker({multiple:false,types:[{description:'Markdown',accept:{'text/markdown':['.md'],'text/plain':['.md']}}]});if(!list.length)return;var h=list[0],t=await(await h.getFile()).text();if(k==='settings')importSettings(t);else importData(t);handles[k]=h;await handleSave(k,h);notice('Linked '+h.name+'. Future automatic reload depends on retained browser permission.');return}catch(e){if(e.name==='AbortError')return;notice('Picker unavailable: '+e.message)}
 el('fallbackKind').value=k;el('portableFilePicker').click()}
async function saveFile(k){var name=k==='settings'?'aletheia-rice-intelligence-settings.md':'aletheia-rice-intelligence-data.md',body=k==='settings'?mdSettings():mdData();try{var h=handles[k];if(!h&&typeof window.showSaveFilePicker==='function'){h=await window.showSaveFilePicker({suggestedName:name,types:[{description:'Markdown',accept:{'text/markdown':['.md']}}]});handles[k]=h;await handleSave(k,h)}if(h){var allow=await h.queryPermission({mode:'readwrite'});if(allow!=='granted')allow=await h.requestPermission({mode:'readwrite'});if(allow==='granted'){var w=await h.createWritable();await w.write(body);await w.close();notice('Saved to the explicitly authorised file: '+h.name);return}}}catch(e){if(e.name==='AbortError')return}download(name,body);notice('Downloaded a new Markdown copy. The browser did not silently overwrite Downloads.')}
async function reconnect(){for(var k of ['settings','data']){var h=await handleLoad(k);if(!h)continue;handles[k]=h;try{if((await h.queryPermission({mode:'read'}))==='granted'){var t=await(await h.getFile()).text();if(k==='settings')importSettings(t);else importData(t);notice('Reconnected authorised '+k+' file: '+h.name)}else notice('To reconnect '+k+', select it from Downloads again; permission is not granted.')}catch(e){notice('Select '+k+' from Downloads again: '+e.message)}}}
function acceptWorker(d){if(!Array.isArray(d.observations)){notice('Connected Worker has no v0.3 structured observations. Deploy the updated Worker to capture history.');return}var map=new Map(state.observations.map(function(x){return[id(x),x]})),prev=new Map(state.observations.filter(function(x){return x.kind==='source-check'}).map(function(x){return[x.source_id,x]})),changes=[],added=0;
 d.observations.forEach(function(o){var r=rec(o);if(!r||map.has(id(r)))return;if(r.kind==='source-check'){var old=prev.get(r.source_id);if(old&&old.fingerprint&&r.fingerprint&&old.fingerprint!==r.fingerprint&&old.status==='retrieved'&&r.status==='retrieved')changes.push(r.source_name+' (page text changed; not proof of new release)');prev.set(r.source_id,r)}map.set(id(r),r);added++});
 state.observations=Array.from(map.values()).slice(-2600);var m=d.meta||{};state.runs.push({retrieved_at:m.retrieved_at||new Date().toISOString(),selected:m.selected||0,direct_attempted:m.direct_attempted||0,direct_retrieved:m.direct_retrieved||0,price_candidates:m.price_candidates||0,changed_sources:changes});state.runs=state.runs.slice(-500);store();notice('Saved '+added+' observations and '+changes.length+' changed page fingerprints. Download Data.md for a durable backup.')}
function valid(x){return x.kind==='price'&&x.chart_eligible&&x.status==='user-reviewed'&&x.url&&x.value>0&&(/^\d{4}-\d{2}-\d{2}$/).test(x.observation_date||'')}
function series(x){return[x.source_id,x.origin,x.grade,x.currency,x.unit,x.basis].join('|')}
function paint(){if(!el('ledgerCounts'))return;var all=state.observations,p=all.filter(function(x){return x.kind==='price'}),checks=all.filter(function(x){return x.kind==='source-check'}),approved=p.filter(valid),pick=el('chartSeries'),old=pick.value;
 el('ledgerCounts').textContent=state.runs.length+' research runs · '+checks.length+' source checks · '+p.length+' candidate prices · '+approved.length+' user-reviewed prices';
 var options=Array.from(new Set(approved.map(series)));pick.innerHTML='<option value="">Choose a reviewed series</option>'+options.map(function(x){return '<option value="'+safe(x)+'">'+safe(x.split('|').slice(1,3).join(' · '))+'</option>'}).join('');if(options.includes(old))pick.value=old;
 el('priceReview').innerHTML=p.length?'<div class="table-wrap"><table><thead><tr><th>Date</th><th>Grade</th><th>USD/MT</th><th>Review</th><th>Original</th></tr></thead><tbody>'+p.slice(-100).reverse().map(function(x){return '<tr><td>'+safe(x.observation_date)+'</td><td>'+safe(x.grade)+'</td><td>'+safe(x.value)+'</td><td>'+(valid(x)?'User reviewed':'<button type="button" data-approve="'+safe(id(x))+'">Review & approve</button>')+'</td><td><a data-awinignore rel="noopener noreferrer" target="_blank" href="'+safe(x.url)+'">Source ↗</a></td></tr>'}).join('')+'</tbody></table></div>':'<p>No extracted price candidates. Retrieval status alone cannot produce a price graph.</p>';
 el('recentChecks').innerHTML=checks.length?'<div class="table-wrap"><table><thead><tr><th>Checked UTC</th><th>Source</th><th>Status</th><th>Publication metadata</th></tr></thead><tbody>'+checks.slice(-16).reverse().map(function(x){return '<tr><td>'+safe(x.retrieved_at.slice(0,16))+'</td><td><a data-awinignore rel="noopener noreferrer" target="_blank" href="'+safe(x.url)+'">'+safe(x.source_name)+'</a></td><td>'+safe(x.status)+'</td><td>'+safe(x.publication_date||'Not extracted')+'</td></tr>'}).join('')+'</tbody></table></div>':'<p>No source checks saved yet.</p>';chart()}
function chart(){var value=el('chartSeries').value,box=el('priceGraph');box.replaceChildren();if(!value){box.textContent='Review a dated price against its original source before charting it.';return}var a=state.observations.filter(valid).filter(function(x){return series(x)===value}).sort(function(x,y){return x.observation_date.localeCompare(y.observation_date)});a=Array.from(new Map(a.map(function(x){return[x.observation_date,x]})).values());if(!a.length)return;var min=Math.min.apply(null,a.map(function(x){return x.value})),max=Math.max.apply(null,a.map(function(x){return x.value})),pad=Math.max(1,(max-min)*.1);min=Math.max(0,min-pad);max+=pad;
 var w=680,h=260,l=60,b=40,x=function(i){return l+(w-l-20)*(a.length===1?.5:i/(a.length-1))},y=function(v){return 20+(h-20-b)*(1-(v-min)/(max-min||1))},ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 '+w+' '+h);svg.setAttribute('role','img');svg.setAttribute('aria-label','User-reviewed historical rice price series');svg.style.maxWidth='100%';
 function add(tag,attrs,label){var node=document.createElementNS(ns,tag);Object.keys(attrs).forEach(function(k){node.setAttribute(k,attrs[k])});if(label!=null)node.textContent=label;svg.append(node);return node}add('line',{x1:l,y1:20,x2:l,y2:h-b,stroke:'#63786e'});add('line',{x1:l,y1:h-b,x2:w-20,y2:h-b,stroke:'#63786e'});add('polyline',{points:a.map(function(p,i){return x(i)+','+y(p.value)}).join(' '),fill:'none',stroke:'#21684d','stroke-width':'3'});a.forEach(function(p,i){var n=add('circle',{cx:x(i),cy:y(p.value),r:4,fill:'#21684d'}),t=document.createElementNS(ns,'title');t.textContent=p.observation_date+' '+p.value+' '+p.currency+'/'+p.unit;n.append(t)});add('text',{x:l,y:h-10,fill:'#456254','font-size':12},a[0].observation_date);add('text',{x:w-20,y:h-10,'text-anchor':'end',fill:'#456254','font-size':12},a[a.length-1].observation_date);box.append(svg);var note=document.createElement('p');note.textContent=a.length+' user-reviewed historical observations. Indicative benchmark, not a current supplier offer.';box.append(note)}
function wire(){restore();paint();el('loadData').onclick=function(){load('data')};el('loadSettingsPortable').onclick=function(){load('settings')};el('exportData').onclick=exportData;el('exportSettingsPortable').onclick=exportSettings;el('saveDataLinked').onclick=function(){saveFile('data')};el('saveSettingsLinked').onclick=function(){saveFile('settings')};el('chartSeries').onchange=chart;
 el('portableFilePicker').onchange=async function(e){var f=e.target.files&&e.target.files[0];if(!f)return;try{var t=await f.text();if(el('fallbackKind').value==='settings')importSettings(t);else importData(t)}catch(err){notice('Import failed: '+err.message)}e.target.value=''};
 el('priceReview').addEventListener('click',function(e){var b=e.target.closest('[data-approve]');if(!b)return;var r=state.observations.find(function(x){return id(x)===b.dataset.approve});if(!r)return;window.open(r.url,'_blank','noopener,noreferrer');if(!confirm('Have you checked the ORIGINAL dated row, rice grade/crop year, value, units and trade basis? Only confirm after verification.'))return;r.status='user-reviewed';r.chart_eligible=true;r.verified_at=new Date().toISOString();store();notice('Price marked user-reviewed. Export Data.md to preserve it.')});
 reconnect()}
window.RiceLedger={acceptWorker:acceptWorker,exportData:exportData,exportSettings:exportSettings,importData:importData,importSettings:importSettings,mdData:mdData,mdSettings:mdSettings};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();